/*
    Papyrus, PDF Generation Service for Resuminator
    Copyright (C) 2021 Resuminator Authors

    This file is part of Papyrus.

    Papyrus is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Papyrus is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Papyrus.  If not, see <https://www.gnu.org/licenses/>.
*/

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Papyrus by Resuminator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Papyrus</h1>

        <p className={styles.description}>
          PDF generation service by{" "}
          <a className={styles.link} href={process.env.NEXT_PUBLIC_R8}>
            Resuminator
          </a>
        </p>

        <a href="https://docs.resuminator.in" className={styles.card}>
          <h2>Documentation &rarr;</h2>
          <p>Find out how Papyrus works and its API Reference</p>
        </a>
      </main>

      <footer className={styles.footer}>
        <div className={styles.author}>
          Developed &amp; Maintained by
          <a href={process.env.NEXT_PUBLIC_R8} className={styles.logo}>
            <Image
              src="/text_dark.svg"
              alt="Resuminator"
              height={20}
              width={100}
            />
          </a>
        </div>
      </footer>
    </div>
  );
}
